### ISSUE TITLE
What needs to be done for initial release

### ISSUE THREAD

**Issue by AntJanus** [base-apps/angular-base-apps#1] opened 2016-06-13 17:33 UTC
We need to release angular-base to NPM but before that gets done, there is a lot of work to do, mainly having to do with other open source projects related to Foundation for Apps, and branding as well as deciding on the structure of the leadership behind this fork.

**Comment by soumak77** [comment] 2016-06-13 17:37
It would be a good idea to continue with the decoupling of the framework that was started with https://github.com/zurb/front-router and https://github.com/zurb/motion-ui.  This would help move in the direction of enabling other front end frameworks.  This may not be something needed for the initial release, but should be done sooner than later.

**Comment by AntJanus** [comment] 2016-06-13 17:38
To dos that I can think of:
- [x] update README with new links
- [x] new tests over travis-ci https://travis-ci.org/base-apps/angular-base
- [ ] new documentation needs to live somewhere as well
- [ ] publish NPM/Bower packages

Secondary release:
- [ ] fork https://github.com/zurb/foundation-cli
- [ ] fork https://github.com/zurb/foundation-apps-template, publish it, and reference the new package version here
- [x] update references to `foundation` to say `base` (in the code) but keep an alias for backwards compatibility
- [ ] replace `zf` references with `ab` but keep `zf` alive in the initial release (before a major release)

**Comment by soumak77** [comment] 2016-06-13 18:09
For `new documentation needs to live somewhere as well`, we can use https://pages.github.com.  I've never personally used it, but seems easy enough and this way we don't need an alternate hosting site.

**Comment by mattgrande** [comment] 2016-06-13 18:32
Does this need a CLI for v1? I think we could live without it, personally.

Agreed that github pages is a good solution for documentation.

**Comment by soumak77** [comment] 2016-06-13 18:49
Yeah the CLI is really just a few basic commands.  I would prefer to not have to maintain it in this framework as it was designed specifically for the suite of foundation frameworks.  If we only need to support the one framework, we can integrate the commands into npm scripts or gulp tasks.

**Comment by tolyo** [comment] 2016-06-13 19:11
The CLI is an overkill as its basically a wrapper around npm and a build tool. 
We will need a second repo for `angular-base-website`.

**Comment by soumak77** [comment] 2016-06-13 19:29
I ran the auto generator to produce a template github pages website: http://base-apps.github.io/angular-base.  Updates can be committed to the github pages branch https://github.com/base-apps/angular-base/tree/gh-pages.

**Comment by soumak77** [comment] 2016-06-13 19:30
@tolyo what will `angular-base-website` be needed for?

**Comment by AntJanus** [comment] 2016-06-13 20:06
We definitely don't need to port the CLI right away but I figure that if people got used to using it, I'd want to have a port of it, too. Whoever wants to support it can do so.

@tolyo as far as the `angular-base-website`, would that just be a port of https://github.com/zurb/foundation-apps-template?

**Comment by soumak77** [comment] 2016-06-13 20:44
In terms of version, should we just carry on where foundation apps left off?  Meaning the first release of this framework would be a `1.3` release (or `1.2.1` if it ends up being a drop in replacement).  I wouldn't mind starting the versioning from `1.0`, but not sure if that will be confusing when people migrate.

**Comment by AntJanus** [comment] 2016-06-13 20:56
Let's start from the original numbering. The rebrand should be like a patch: 1.2.1 or something with just READMEs, licenses, etc. updated. When we start adding the new aliases, we should bump it to 1.3 and follow semantic versioning from there.

That way, it's an easy drop-in replacement.

**Comment by soumak77** [comment] 2016-06-13 21:04
Works for me. I'll start working on converting the docs to GitHub pages in a day or two if someone else doesn't get to it first.

**Comment by tolyo** [comment] 2016-06-14 06:16
@AntJanus @soumak77 I was thinking of keeping documentation separate from the framework. I guess ghpages works just fine at this point.

**Comment by laurent-le-graverend** [comment] 2016-06-14 06:58
Congrats for moving this here,

About documentation, I believe most of beginners would still bet on Foundation for Apps, which is probably fine for them for the moment. You want to drive advanced developers attention first, before they would be the one to drive bugs reports and fixes.

The big miss on Foundation for Apps documentation is to not be enough API oriented.
They build a nice way to build and communicate across components, and I guess this is where a good documentation would matters.

`new Modal()` vs `<zf-modal>...`

**Comment by soumak77** [comment] 2016-06-14 15:00
@laurent-le-graverend I agree the API documentation is really poor.  I've created issue #4 to discuss documentation changes.

**Comment by soumak77** [comment] 2016-06-14 15:06
@AntJanus We can likely push the documentation changes to the next release.  Foundation for Apps docs should be appropriate for now since we won't be making any framework changes.

With that said, we may be able to push a release very shortly.  Is there anything else we are waiting on other than verifying all tests are passing?

**Comment by AntJanus** [comment] 2016-06-14 16:21
@soumak77 nothing at all! We can push it out to NPM and Bower as soon as we merge in the docs.

**Comment by soumak77** [comment] 2016-06-14 17:23
@AntJanus when you say `merge in the docs`, what are you referring to?  Seems as though we can just remove the docs from the repo entirely.  Docs will have to be maintained in a different branch anyway, specifically https://github.com/base-apps/angular-base/tree/gh-pages.

**Comment by soumak77** [comment] 2016-07-14 11:02
Initial [v1.2.1](https://github.com/base-apps/angular-base/releases/tag/v1.2.1) release has been published.  Due to a conflict in the bower registry, the package has been published under `angular-base-apps`.

**Closed as completed by soumak77** 2016-07-14 11:02 UTC
