### ISSUE TITLE
On 1.2.6, setting $notification-default-position does not work

### ISSUE THREAD

**Issue by mattheworres** [base-apps/angular-base-apps#89] opened 2016-12-21 14:18 UTC
Given that I set the SASS variable `$notification-default-position` from something different from the default of `top right` (to `middle bottom`, for example) any and all notifications without a `position` attribute specified still show up in the top right.

**Comment by soumak77** [comment] 2016-12-28 11:07
The issue is caused by the code using the class `top-right` when no position is provided:
- https://github.com/base-apps/angular-base-apps/tree/master/js/angular/components/notification/notification.js#L89
- https://github.com/base-apps/angular-base-apps/tree/master/js/angular/components/notification/notification.js#L245

This should be changed to use a `default-position` class instead so the default position is taken from the SASS variable.  The following styling should be added under `.static-notification` and `.notification-container` in https://github.com/base-apps/angular-base-apps/blob/master/scss/components/_notification.scss.

```scss
&.default-position     { @include notification-layout(); }
```

**Comment by soumak77** [comment] 2017-01-23 20:05
fixed by https://github.com/base-apps/angular-base-apps/commit/d30e8b4a64d5c76f6e2bd29708c35d3e9d5bf38c

**Closed as completed by soumak77** 2017-01-23 20:05 UTC
Labels: bug, help wanted
